DB_NAME_DEFAULT='scilabdb'
DB_USER_DEFAULT='root'
DB_PASS_DEFAULT='master'
DB_HOST_DEFAULT=''
DB_PORT_DEFAULT=''


DB_NAME_SCILAB='scilabdb'
DB_USER_SCILAB='root'
DB_PASS_SCILAB='master'
DB_HOST_SCILAB=''
DB_PORT_SCILAB=''
